### ISSUE TITLE
Installation of ntp has issue (not native service)

### ISSUE THREAD

**Issue by norbertvannobelen** [norbertvannobelen/kube-gcp-deployment#5]
ntp.service is not a native service, redirecting to systemd-sysv-install
Executing /lib/systemd/systemd-sysv-install enable ntp
Connection to 35.227.42.228 closed.
+ sudo systemctl start ntp
Failed to start ntp.service: Unit ntp.service failed to load: No such file or directory.

**Comment by nvnobelen** [comment]
Solved
